/**
 *
 *  Copyright 2012-2017 the original author or authors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.18 at 09:59:48 AM EDT 
//


package com.anthem.nimbus.platform.core.process.api.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for get_278_ResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="get_278_ResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="get_278_X12_Response" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="get_999_X12_Response" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="get_TA1_X12_Response" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "get_278_ResponseType", propOrder = {
    "get278X12Response",
    "get999X12Response",
    "getTA1X12Response"
})
public class Get278ResponseType {

    @XmlElement(name = "get_278_X12_Response")
    protected byte[] get278X12Response;
    @XmlElement(name = "get_999_X12_Response")
    protected byte[] get999X12Response;
    @XmlElement(name = "get_TA1_X12_Response")
    protected byte[] getTA1X12Response;

    /**
     * Gets the value of the get278X12Response property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getGet278X12Response() {
        return get278X12Response;
    }

    /**
     * Sets the value of the get278X12Response property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setGet278X12Response(byte[] value) {
        this.get278X12Response = ((byte[]) value);
    }

    /**
     * Gets the value of the get999X12Response property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getGet999X12Response() {
        return get999X12Response;
    }

    /**
     * Sets the value of the get999X12Response property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setGet999X12Response(byte[] value) {
        this.get999X12Response = ((byte[]) value);
    }

    /**
     * Gets the value of the getTA1X12Response property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getGetTA1X12Response() {
        return getTA1X12Response;
    }

    /**
     * Sets the value of the getTA1X12Response property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setGetTA1X12Response(byte[] value) {
        this.getTA1X12Response = ((byte[]) value);
    }

}
