/**
 *  Copyright 2016-2018 the original author or authors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 12:04:06 PM EDT 
//


package com.anthem.nimbus.platform.core.process.api.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.anthem.nimbus.platform.core.process.sample.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.anthem.nimbus.platform.core.process.sample.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SearchMemberResponse.DynamicData }
     * 
     */
    public SearchMemberResponse.DynamicData createSearchMemberResponseDynamicData() {
        return new SearchMemberResponse.DynamicData();
    }

    /**
     * Create an instance of {@link SearchMemberResponse.DynamicData.Products.BenefitClass }
     * 
     */
    public SearchMemberResponse.DynamicData.Products.BenefitClass createSearchMemberResponseDynamicDataProductsBenefitClass() {
        return new SearchMemberResponse.DynamicData.Products.BenefitClass();
    }

    /**
     * Create an instance of {@link SearchMemberRequest.StaticData.GrpLkup }
     * 
     */
    public SearchMemberRequest.StaticData.GrpLkup createSearchMemberRequestStaticDataGrpLkup() {
        return new SearchMemberRequest.StaticData.GrpLkup();
    }

    /**
     * Create an instance of {@link SearchMemberResponse.DynamicData.PhysicalAddress }
     * 
     */
    public SearchMemberResponse.DynamicData.PhysicalAddress createSearchMemberResponseDynamicDataPhysicalAddress() {
        return new SearchMemberResponse.DynamicData.PhysicalAddress();
    }

    /**
     * Create an instance of {@link SearchMemberResponse.DynamicData.Products.GraceInfo.Notes }
     * 
     */
    public SearchMemberResponse.DynamicData.Products.GraceInfo.Notes createSearchMemberResponseDynamicDataProductsGraceInfoNotes() {
        return new SearchMemberResponse.DynamicData.Products.GraceInfo.Notes();
    }

    /**
     * Create an instance of {@link SearchMemberRequest }
     * 
     */
    public SearchMemberRequest createSearchMemberRequest() {
        return new SearchMemberRequest();
    }

    /**
     * Create an instance of {@link SearchMemberResponse.DynamicData.Subscriber }
     * 
     */
    public SearchMemberResponse.DynamicData.Subscriber createSearchMemberResponseDynamicDataSubscriber() {
        return new SearchMemberResponse.DynamicData.Subscriber();
    }

    /**
     * Create an instance of {@link SearchMemberResponse.DynamicData.Member }
     * 
     */
    public SearchMemberResponse.DynamicData.Member createSearchMemberResponseDynamicDataMember() {
        return new SearchMemberResponse.DynamicData.Member();
    }

    /**
     * Create an instance of {@link SearchMemberRequest.StaticData }
     * 
     */
    public SearchMemberRequest.StaticData createSearchMemberRequestStaticData() {
        return new SearchMemberRequest.StaticData();
    }

    /**
     * Create an instance of {@link SearchMemberResponse }
     * 
     */
    public SearchMemberResponse createSearchMemberResponse() {
        return new SearchMemberResponse();
    }

    /**
     * Create an instance of {@link SearchMemberResponse.DynamicData.CoverageTypeArray }
     * 
     */
    public SearchMemberResponse.DynamicData.CoverageTypeArray createSearchMemberResponseDynamicDataCoverageTypeArray() {
        return new SearchMemberResponse.DynamicData.CoverageTypeArray();
    }

    /**
     * Create an instance of {@link SearchMemberResponse.DynamicData.Products }
     * 
     */
    public SearchMemberResponse.DynamicData.Products createSearchMemberResponseDynamicDataProducts() {
        return new SearchMemberResponse.DynamicData.Products();
    }

    /**
     * Create an instance of {@link SearchMemberResponse.DynamicData.Products.GraceInfo }
     * 
     */
    public SearchMemberResponse.DynamicData.Products.GraceInfo createSearchMemberResponseDynamicDataProductsGraceInfo() {
        return new SearchMemberResponse.DynamicData.Products.GraceInfo();
    }

    /**
     * Create an instance of {@link SearchMemberResponse.DynamicData.CrdInfo }
     * 
     */
    public SearchMemberResponse.DynamicData.CrdInfo createSearchMemberResponseDynamicDataCrdInfo() {
        return new SearchMemberResponse.DynamicData.CrdInfo();
    }

    /**
     * Create an instance of {@link SearchMemberResponse.DynamicData.MemberAddress }
     * 
     */
    public SearchMemberResponse.DynamicData.MemberAddress createSearchMemberResponseDynamicDataMemberAddress() {
        return new SearchMemberResponse.DynamicData.MemberAddress();
    }

    /**
     * Create an instance of {@link SearchMemberResponse.DynamicData.VoidRecord }
     * 
     */
    public SearchMemberResponse.DynamicData.VoidRecord createSearchMemberResponseDynamicDataVoidRecord() {
        return new SearchMemberResponse.DynamicData.VoidRecord();
    }

    /**
     * Create an instance of {@link SearchMemberResponse.DynamicData.ClientIndicator }
     * 
     */
    public SearchMemberResponse.DynamicData.ClientIndicator createSearchMemberResponseDynamicDataClientIndicator() {
        return new SearchMemberResponse.DynamicData.ClientIndicator();
    }

    /**
     * Create an instance of {@link SearchMemberResponse.DynamicData.Products.CDHP }
     * 
     */
    public SearchMemberResponse.DynamicData.Products.CDHP createSearchMemberResponseDynamicDataProductsCDHP() {
        return new SearchMemberResponse.DynamicData.Products.CDHP();
    }

}