//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.25 at 12:04:06 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://wellpoint.com/schema/SearchMemberRequest/v9.02", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.anthem.nimbus.platform.core.process.api.wsdl;