/**
 *
 *  Copyright 2012-2017 the original author or authors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 

package com.anthem.nimbus.platform.core.process.api.wsdl;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="StaticData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="memberLookupId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="mbrSqncNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="GrpLkup" maxOccurs="2" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="grpLkupId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="grpLkupIdTypCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="birthDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="activeInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="productFamilyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="eligibilityTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="subscriberId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="serviceStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="searchStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="searchEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="financialCompanyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="benefitPlanId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="suppressionOverrideTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="sourceSystemIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "staticData"
})
@XmlRootElement(name = "SearchMemberRequest")
public class SearchMemberRequest {

    @XmlElement(name = "StaticData")
    protected SearchMemberRequest.StaticData staticData;

    /**
     * Gets the value of the staticData property.
     * 
     * @return
     *     possible object is
     *     {@link SearchMemberRequest.StaticData }
     *     
     */
    public SearchMemberRequest.StaticData getStaticData() {
        return staticData;
    }

    /**
     * Sets the value of the staticData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchMemberRequest.StaticData }
     *     
     */
    public void setStaticData(SearchMemberRequest.StaticData value) {
        this.staticData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="memberLookupId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="mbrSqncNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="GrpLkup" maxOccurs="2" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="grpLkupId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="grpLkupIdTypCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="birthDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="activeInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="productFamilyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="eligibilityTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="subscriberId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="serviceStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="searchStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="searchEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="financialCompanyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="benefitPlanId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="suppressionOverrideTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="sourceSystemIdentifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "memberLookupId",
        "mbrSqncNum",
        "grpLkup",
        "birthDate",
        "activeInd",
        "productFamilyCode",
        "eligibilityTypeCode",
        "subscriberId",
        "lastName",
        "firstName",
        "serviceStartDate",
        "searchStartDate",
        "searchEndDate",
        "financialCompanyCode",
        "benefitPlanId",
        "suppressionOverrideTypeCode",
        "sourceSystemIdentifier"
    })
    public static class StaticData {

        protected String memberLookupId;
        protected String mbrSqncNum;
        @XmlElement(name = "GrpLkup")
        protected List<SearchMemberRequest.StaticData.GrpLkup> grpLkup;
        protected String birthDate;
        protected String activeInd;
        protected String productFamilyCode;
        protected String eligibilityTypeCode;
        protected String subscriberId;
        protected String lastName;
        protected String firstName;
        protected String serviceStartDate;
        protected String searchStartDate;
        protected String searchEndDate;
        protected String financialCompanyCode;
        protected String benefitPlanId;
        protected String suppressionOverrideTypeCode;
        protected String sourceSystemIdentifier;

        /**
         * Gets the value of the memberLookupId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMemberLookupId() {
            return memberLookupId;
        }

        /**
         * Sets the value of the memberLookupId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMemberLookupId(String value) {
            this.memberLookupId = value;
        }

        /**
         * Gets the value of the mbrSqncNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMbrSqncNum() {
            return mbrSqncNum;
        }

        /**
         * Sets the value of the mbrSqncNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMbrSqncNum(String value) {
            this.mbrSqncNum = value;
        }

        /**
         * Gets the value of the grpLkup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the grpLkup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGrpLkup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SearchMemberRequest.StaticData.GrpLkup }
         * 
         * 
         */
        public List<SearchMemberRequest.StaticData.GrpLkup> getGrpLkup() {
            if (grpLkup == null) {
                grpLkup = new ArrayList<SearchMemberRequest.StaticData.GrpLkup>();
            }
            return this.grpLkup;
        }

        /**
         * Gets the value of the birthDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBirthDate() {
            return birthDate;
        }

        /**
         * Sets the value of the birthDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBirthDate(String value) {
            this.birthDate = value;
        }

        /**
         * Gets the value of the activeInd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActiveInd() {
            return activeInd;
        }

        /**
         * Sets the value of the activeInd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActiveInd(String value) {
            this.activeInd = value;
        }

        /**
         * Gets the value of the productFamilyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductFamilyCode() {
            return productFamilyCode;
        }

        /**
         * Sets the value of the productFamilyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductFamilyCode(String value) {
            this.productFamilyCode = value;
        }

        /**
         * Gets the value of the eligibilityTypeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEligibilityTypeCode() {
            return eligibilityTypeCode;
        }

        /**
         * Sets the value of the eligibilityTypeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEligibilityTypeCode(String value) {
            this.eligibilityTypeCode = value;
        }

        /**
         * Gets the value of the subscriberId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubscriberId() {
            return subscriberId;
        }

        /**
         * Sets the value of the subscriberId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubscriberId(String value) {
            this.subscriberId = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the serviceStartDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServiceStartDate() {
            return serviceStartDate;
        }

        /**
         * Sets the value of the serviceStartDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServiceStartDate(String value) {
            this.serviceStartDate = value;
        }

        /**
         * Gets the value of the searchStartDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSearchStartDate() {
            return searchStartDate;
        }

        /**
         * Sets the value of the searchStartDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSearchStartDate(String value) {
            this.searchStartDate = value;
        }

        /**
         * Gets the value of the searchEndDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSearchEndDate() {
            return searchEndDate;
        }

        /**
         * Sets the value of the searchEndDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSearchEndDate(String value) {
            this.searchEndDate = value;
        }

        /**
         * Gets the value of the financialCompanyCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFinancialCompanyCode() {
            return financialCompanyCode;
        }

        /**
         * Sets the value of the financialCompanyCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFinancialCompanyCode(String value) {
            this.financialCompanyCode = value;
        }

        /**
         * Gets the value of the benefitPlanId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBenefitPlanId() {
            return benefitPlanId;
        }

        /**
         * Sets the value of the benefitPlanId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBenefitPlanId(String value) {
            this.benefitPlanId = value;
        }

        /**
         * Gets the value of the suppressionOverrideTypeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSuppressionOverrideTypeCode() {
            return suppressionOverrideTypeCode;
        }

        /**
         * Sets the value of the suppressionOverrideTypeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSuppressionOverrideTypeCode(String value) {
            this.suppressionOverrideTypeCode = value;
        }

        /**
         * Gets the value of the sourceSystemIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceSystemIdentifier() {
            return sourceSystemIdentifier;
        }

        /**
         * Sets the value of the sourceSystemIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceSystemIdentifier(String value) {
            this.sourceSystemIdentifier = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="grpLkupId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="grpLkupIdTypCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "grpLkupId",
            "grpLkupIdTypCd"
        })
        public static class GrpLkup {

            protected String grpLkupId;
            protected String grpLkupIdTypCd;

            /**
             * Gets the value of the grpLkupId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGrpLkupId() {
                return grpLkupId;
            }

            /**
             * Sets the value of the grpLkupId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGrpLkupId(String value) {
                this.grpLkupId = value;
            }

            /**
             * Gets the value of the grpLkupIdTypCd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGrpLkupIdTypCd() {
                return grpLkupIdTypCd;
            }

            /**
             * Sets the value of the grpLkupIdTypCd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGrpLkupIdTypCd(String value) {
                this.grpLkupIdTypCd = value;
            }

        }

    }

}
