/**
 *
 *  Copyright 2016-2019 the original author or authors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.antheminc.oss.nimbus.domain.rules;

import com.antheminc.oss.nimbus.domain.model.state.EntityState.Param;
import com.antheminc.oss.nimbus.domain.model.state.internal.DefaultParamState;
import java.time.LocalDate;
import java.time.Period;

import function com.antheminc.oss.nimbus.domain.rules.drools.DroolsLoggerUtil.*;

rule "SampleChangeLogView Rule Test 1"
   when
   		$view : DefaultParamState($view.findParamByPath("/vpSampleCoreChangeLog/vtSampleCoreChangeLog/vsSampleCoreChangeLog/vfSampleCoreChangeLog/status").getState() == 'Test_Status')
   then
   		info(drools, " SampleChangeLogView param 'status' has state "+$view.findParamByPath("/vpSampleCoreChangeLog/vtSampleCoreChangeLog/vsSampleCoreChangeLog/vfSampleCoreChangeLog/status").getState());
   		
   		$view.findParamByPath("/vpSampleCoreChangeLog/vtSampleCoreChangeLog/vsSampleCoreChangeLog/vfSampleCoreChangeLog/statusSetViaRule").setState("Test_Status_Via_Rule");
   		
   		info(drools, " SampleChangeLogView param 'statusSetViaRule' has state "+$view.findParamByPath("/vpSampleCoreChangeLog/vtSampleCoreChangeLog/vsSampleCoreChangeLog/vfSampleCoreChangeLog/statusSetViaRule").getState());
   		info(drools, " SampleChangeLogCore param 'statusSetViaRule' has state "+$view.findParamByPath("/.m/statusSetViaRule").getState());
   end
   
   
   
   