/**
 *
 *  Copyright 2016-2019 the original author or authors.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

import com.antheminc.oss.nimbus.domain.model.state.internal.DefaultParamState;

rule "Rule State Event Handler Test: Sample Increment"
when
    $core : DefaultParamState();
    $param : DefaultParamState() from $core.findParamByPath("../rule_param_affectState");
then
	if (null != $param.getState()) {
		$param.setState(((Integer) $param.getState()) + 1);
	} else {
		$param.setState(1);
	}
end