package com.anthem.nimbus.platform.client.extension.cm.model.sample

import com.anthem.oss.nimbus.core.domain.model.state.internal.DefaultParamState;

rule "Sample Rule 1"
no-loop true
when
    $core : DefaultParamState()
then
	System.out.println("Incrementing");
	$core.findParamByPath("/rule_param_affectState").setState(((Integer) $core.findParamByPath("/rule_param_affectState").getState()) + 1);
end