package com.anthem.nimbus.platform.client.extension.cm.model.sample

import com.anthem.oss.nimbus.core.domain.model.state.internal.DefaultParamState;

rule "Rule State Event Handler Test: Sample Increment"
when
    $core : DefaultParamState();
    $param : DefaultParamState() from $core.findParamByPath("../rule_param_affectState");
then
	if (null != $param.getState()) {
		$param.setState(((Integer) $param.getState()) + 1);
	} else {
		$param.setState(1);
	}
end