package com.anthem.nimbus.platform.core.rules

import com.antheminc.oss.nimbus.core.domain.model.state.internal.DefaultModelState;
import com.antheminc.oss.nimbus.core.domain.model.state.EntityState.Param;
import com.antheminc.oss.nimbus.core.domain.model.state.internal.DefaultParamState;
import java.time.LocalDate;
import java.time.Period;

rule "Core Rule Test 1"
   when
   	$core : DefaultParamState($core.findParamByPath("/triggerParameter").getState() == 'Start')
   	$state : RuleTestCoreModel()
   then
   	   $core.findParamByPath("/triggeredParameter").setState("Triggered");   
   	   $state.setStateCheckParameter("Executed");   
   end